alias ls='ls -alhF --color=auto'
alias grep='grep --color=auto'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
alias ln='ln -i'
alias ping='ping -c 5'
alias du='du -c -h'
alias mkdir='mkdir -p -v'
alias ip='ip -c'
alias exa='exa -alH'
alias testing-repo='pacman --color=always -Sl {,community-}testing|grep -F "[installed]"'
alias custom-repo='pacman --color=always -Sl custom|grep -F "[installed]"'
