#!/bin/sh

[[ -f ~/.config/X11/Xresources ]] && xrdb -merge -I$HOME ~/.config/X11/Xresources
#[[ -f ~/.session-errors ]] && mv ~/.xsession-errors ~/.xsession-errors.old

# Source .profile
#[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.profile ] && . ~/.profile

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset s off -dpms
xset r rate 200 40
setxkbmap -option caps:swapescape
setxkbmap -option terminate:ctrl_alt_bksp

# Set a default DE/WM
# or pick one manually: startx ~/.xinitrc session
session=${1:-i3}

case $session in
    cinnamon        ) exec cinnamon-session;;
    cinnamon2d      ) exec cinnamon-session-cinnamon2d;;
    i3|i3wm         ) exec i3;;
    awesome         ) exec awesome;;
    # No known session, try to run it as command
    *               ) exec $1;;
esac
